import { useState, useEffect, useRef, useCallback } from 'react';
import { View, Text, ScrollView, TouchableOpacity, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter, useFocusEffect } from 'expo-router';
import { supabase } from '@/lib/supabase';
import {
  fetchLatestReflection,
  fetchMonthlyReflectionCount,
  fetchUserSelections,
  generateReflections,
} from '@/lib/api';
import { ReflectionCard } from '@/components/ReflectionCard';
import { Colors } from '@/constants/theme';

const MONTHLY_LIMIT = 6;

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

function nextMonthName() {
  const d = new Date();
  d.setMonth(d.getMonth() + 1);
  return d.toLocaleDateString('en-GB', { month: 'long' });
}

export default function ReflectionsScreen() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [userId, setUserId] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => setUserId(data.user?.id ?? null));
  }, []);

  const { data: latestReflection, isLoading: reflLoading } = useQuery({
    queryKey: ['latest-reflection', userId],
    queryFn: () => fetchLatestReflection(userId!),
    enabled: !!userId,
  });

  const { data: monthlyCount = 0 } = useQuery({
    queryKey: ['monthly-reflection-count', userId],
    queryFn: () => fetchMonthlyReflectionCount(userId!),
    enabled: !!userId,
  });

  const { data: selectedIds = [], isLoading: selectionsLoading } = useQuery({
    queryKey: ['user-selections', userId],
    queryFn: () => fetchUserSelections(userId!),
    enabled: !!userId,
  });

  const isLoading = reflLoading || selectionsLoading;
  const hasThemes = selectedIds.length > 0;
  const atLimit = monthlyCount >= MONTHLY_LIMIT;
  const reflections = latestReflection ? (latestReflection.content as string[]) : null;

  async function handleGenerate() {
    if (!userId || generating || atLimit) return;
    setGenerating(true);
    setGenError('');
    try {
      await generateReflections(userId);
      await queryClient.invalidateQueries({ queryKey: ['latest-reflection', userId] });
      await queryClient.invalidateQueries({ queryKey: ['monthly-reflection-count', userId] });
    } catch (err: any) {
      setGenError(err?.message ?? JSON.stringify(err) ?? "Something went wrong.");
    } finally {
      setGenerating(false);
    }
  }

  // Auto-generate on first visit if user has themes but no reflections yet
  useEffect(() => {
    if (!userId || isLoading || hasAutoGenerated.current) return;
    if (latestReflection) return;
    if (!hasThemes || atLimit) return;
    hasAutoGenerated.current = true;
    handleGenerate();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, isLoading, latestReflection, hasThemes, atLimit]);

  useFocusEffect(
    useCallback(() => {
      if (!userId) return;
      queryClient.invalidateQueries({ queryKey: ['latest-reflection', userId] });
      queryClient.invalidateQueries({ queryKey: ['monthly-reflection-count', userId] });
      queryClient.invalidateQueries({ queryKey: ['user-selections', userId] });
    }, [userId, queryClient])
  );

  // Full-screen loader: initial data fetch OR first-ever generation
  if (isLoading || (generating && !reflections)) {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: Colors.background }} edges={['top']}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 }}>
          <ActivityIndicator color={Colors.primary} size="large" />
          <Text
            style={{
              marginTop: 20,
              fontSize: 16,
              color: Colors.text,
              textAlign: 'center',
              lineHeight: 26,
              fontFamily: 'Georgia',
            }}
          >
            {generating
              ? "We're shaping something thoughtful for you…"
              : 'Loading your reflections…'}
          </Text>
        </View>
      </SafeAreaView>
    );
  }

  // No themes selected
  if (!hasThemes) {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: Colors.background }} edges={['top']}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32 }}>
          <Text
            style={{
              fontFamily: 'Georgia',
              fontSize: 22,
              color: Colors.primary,
              textAlign: 'center',
              marginBottom: 12,
            }}
          >
            Choose your themes first
          </Text>
          <Text
            style={{
              fontSize: 15,
              color: Colors.subtext,
              textAlign: 'center',
              lineHeight: 24,
              marginBottom: 32,
            }}
          >
            Head to the Themes tab to select your ADOPT themes, then return here to generate your reflections.
          </Text>
          <TouchableOpacity
            onPress={() => router.push('/(tabs)/adopt')}
            style={{
              backgroundColor: Colors.primary,
              borderRadius: 14,
              paddingHorizontal: 28,
              minHeight: 50,
              justifyContent: 'center',
              alignItems: 'center',
            }}
            activeOpacity={0.85}
          >
            <Text style={{ color: 'white', fontSize: 15, fontWeight: '600' }}>Choose Themes</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const remaining = MONTHLY_LIMIT - monthlyCount;

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: Colors.background }} edges={['top']}>
      <ScrollView
        contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 120 }}
        showsVerticalScrollIndicator={false}
      >
        {/* Header */}
        <View style={{ paddingTop: 12, marginBottom: 20 }}>
          <Text style={{ fontFamily: 'Georgia', fontSize: 28, color: Colors.primary, lineHeight: 36 }}>
            Points of Reflection
          </Text>
          {latestReflection && (
            <Text style={{ fontSize: 13, color: Colors.subtext, marginTop: 4 }}>
              Generated {formatDate(latestReflection.generated_at)}
            </Text>
          )}
        </View>

        {/* Monthly usage banner */}
        <View
          style={{
            backgroundColor: atLimit ? Colors.error + '15' : Colors.accent + '25',
            borderRadius: 10,
            paddingHorizontal: 14,
            paddingVertical: 10,
            marginBottom: 24,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}
        >
          {atLimit ? (
            <Text style={{ fontSize: 13, color: Colors.text, lineHeight: 20, flex: 1 }}>
              You've used all {MONTHLY_LIMIT} reflections for this month. Resets in {nextMonthName()}.
            </Text>
          ) : (
            <>
              <Text style={{ fontSize: 13, color: Colors.text }}>
                {monthlyCount} of {MONTHLY_LIMIT} reflections used this month
              </Text>
              <Text style={{ fontSize: 13, color: Colors.subtext }}>
                {remaining} left
              </Text>
            </>
          )}
        </View>

        {/* Reflection cards */}
        {reflections ? (
          reflections.map((text, i) => (
            <ReflectionCard key={i} text={text} index={i} />
          ))
        ) : (
          <View style={{ alignItems: 'center', paddingTop: 32 }}>
            <Text style={{ color: Colors.subtext, fontSize: 15, textAlign: 'center' }}>
              Your reflections will appear here once selected
            </Text>
          </View>
        )}

        {genError ? (
          <Text
            style={{
              color: Colors.error,
              fontSize: 14,
              marginTop: 8,
              marginBottom: 4,
              textAlign: 'center',
            }}
          >
            {genError}
          </Text>
        ) : null}
      </ScrollView>

      {/* Sticky bottom action */}
      <View
        style={{
          position: 'absolute',
          bottom: 0,
          left: 0,
          right: 0,
          paddingHorizontal: 20,
          paddingTop: 12,
          paddingBottom: 20,
          backgroundColor: Colors.background,
          borderTopWidth: 1,
          borderTopColor: Colors.secondary + '60',
        }}
      >
        <TouchableOpacity
          onPress={handleGenerate}
          disabled={generating || atLimit}
          style={{
            backgroundColor: atLimit ? Colors.subtext + 'AA' : Colors.primary,
            borderRadius: 14,
            minHeight: 52,
            alignItems: 'center',
            justifyContent: 'center',
            opacity: generating ? 0.7 : 1,
          }}
          activeOpacity={atLimit ? 1 : 0.85}
        >
          {generating ? (
            <ActivityIndicator color="white" />
          ) : (
            <Text style={{ color: 'white', fontSize: 16, fontWeight: '600' }}>
              {atLimit
                ? 'Monthly limit reached'
                : reflections
                ? 'Regenerate'
                : 'Generate Reflections'}
            </Text>
          )}
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}
