-- Re-seed adopt_themes with correct data from ADOPT_DATABASE_280426.xlsx
-- Clears AI-generated placeholder data and replaces with accurate source content

truncate table adopt_themes restart identity cascade;

insert into adopt_themes (category, theme, description, third_person_description, category_colour) values

-- Creativity, culture and legacy (5 themes)
('Creativity, culture and legacy', 'Creative expression', 'I want to express who I am through creativity, ideas or imagination.', 'Creativity provides a way to process emotions, experiment with identity, and explore alternative perspectives. This theme recognises creative acts as both playful and profound — offering freedom, insight and connection beyond words, productivity or conventional outcomes.', '#E6CFF1'),
('Creativity, culture and legacy', 'Cultural and heritage', 'I want to feel connected to my roots, traditions or shared stories.', 'Cultural identity can anchor people across generations, migrations and change. This theme reflects how traditions, language and shared history influence belonging and self-understanding. Engaging with heritage may involve pride, questioning, healing or reclaiming narratives that were previously overlooked.', '#E6CFF1'),
('Creativity, culture and legacy', 'Environment', 'I want to feel more connected to nature and the world around me.', 'Environmental concern connects personal choices with long-term collective outcomes. This theme reflects awareness of interdependence between humans and nature, prompting lifestyle decisions, advocacy or stewardship. It often carries ethical, emotional and generational dimensions tied to responsibility and hope.', '#E6CFF1'),
('Creativity, culture and legacy', 'Hobbies & leisure', 'I want to spend more time doing things I enjoy and that help me relax.', 'Leisure activities provide relief from obligation and performance. This theme recognises the restorative power of play, curiosity and enjoyment, particularly in busy or demanding lives. It highlights how non-productive time can enhance creativity, resilience and overall quality of life.', '#E6CFF1'),
('Creativity, culture and legacy', 'Legacy', 'I want to create something meaningful that lasts or positively impacts others.', 'Legacy is not limited to end-of-life reflection. This theme explores how daily actions, relationships and contributions accumulate over time. It invites consideration of influence, memory and impact — both intentional and unintended — across generations and communities.', '#E6CFF1'),

-- Health and wellbeing (6 themes)
('Health and wellbeing', 'Health', 'I want to take better care of my physical and mental health.', 'Health encompasses more than absence of illness. This theme reflects ongoing attention to energy, balance and sustainability — physically and mentally. It often involves preventive habits, self-awareness and navigating trade-offs between performance, rest and long-term wellbeing.', '#A7D7C5'),
('Health and wellbeing', 'Living with disability', 'I''m living with a condition that shapes how I experience the world and access opportunities.', 'Disability can shape how individuals interact with environments, systems and relationships. This theme highlights resilience, adaptation and advocacy, while recognising the social barriers that often matter more than impairment itself. It reflects lived experience, dignity and the pursuit of equity.', '#A7D7C5'),
('Health and wellbeing', 'Managing pain', 'I want to manage or cope better with physical or emotional pain.', 'Pain management involves navigating physical sensations, emotional responses and limitations. This theme recognises the complexity of chronic or acute pain, the search for effective strategies, and the effort required to preserve autonomy, identity and quality of life.', '#A7D7C5'),
('Health and wellbeing', 'Morbidity, ill health', 'I''m living with a health condition that affects my daily life and routines.', 'Living with ongoing health conditions often reshapes routines, priorities and self-image. This theme acknowledges the invisible labour of adaptation, the emotional impact of limitation, and the need to balance acceptance with advocacy, while continuing to find meaning and agency in daily life.', '#A7D7C5'),
('Health and wellbeing', 'Surviving crises', 'I''m getting through a difficult time and looking for ways to rebuild.', 'Crises can disrupt assumptions, routines and identity. This theme reflects navigating shock, uncertainty and recovery, often requiring support and adaptation. It acknowledges that survival may precede understanding, and that rebuilding meaning and direction can take significant time.', '#A7D7C5'),
('Health and wellbeing', 'Wellbeing', 'I want to feel more balanced and fulfilled in all parts of life.', 'Wellbeing integrates emotional, physical, social and psychological dimensions of life. This theme recognises balance as dynamic rather than fixed, shaped by context and self-awareness. It invites reflection on sustainability, fulfilment and how different aspects of life support one another.', '#A7D7C5'),

-- Lifework and resilience (10 themes)
('Lifework and resilience', 'Bouncebackability', 'I want to recover from setbacks and keep moving forward with strength.', 'Recovery from adversity is rarely a straight line. This theme reflects learning how to adapt expectations, rebuild confidence, and move forward without denying what has been lost or changed. It often involves patience, self-compassion, and discovering new strengths that only emerge through challenge.', '#C1C8E4'),
('Lifework and resilience', 'Competitiveness', 'I''m driven to grow, succeed and push myself to achieve more.', 'Competitive drive can motivate progress, learning and excellence, but may also create pressure or comparison. This theme explores how ambition is shaped by context, self-worth and expectations, and invites reflection on what success means when measured internally rather than purely against others.', '#C1C8E4'),
('Lifework and resilience', 'Entrepreneurship', 'I want to create something new - an idea, a project, a way of working.', 'Entrepreneurship is as much about mindset as venture creation. This theme explores navigating uncertainty, risk and responsibility while transforming ideas into reality. It often involves experimentation, resilience and learning from failure, alongside the freedom to shape work around personal values and vision.', '#C1C8E4'),
('Lifework and resilience', 'Home', 'I want to feel safe, grounded and at home - wherever I am.', 'Home represents more than a physical space — it carries emotional safety, memory and identity. This theme explores how people create belonging through place, routine or community, especially during transitions, relocation or periods of instability.', '#C1C8E4'),
('Lifework and resilience', 'Learning', 'I want to keep learning, growing and developing throughout my life.', 'Learning extends beyond formal education into lived experience. This theme reflects curiosity, adaptability and growth across life stages. It recognises learning as a tool for reinvention, confidence-building and staying engaged in a rapidly changing world.', '#C1C8E4'),
('Lifework and resilience', 'Money', 'I want to feel more in control of my finances and the choices they enable.', 'Money influences choice, security and opportunity. This theme explores emotional relationships with finances, including stress, freedom and responsibility. It invites reflection on values, priorities and trade-offs, recognising that financial wellbeing is deeply connected to broader life stability.', '#C1C8E4'),
('Lifework and resilience', 'Security', 'I want to feel more stable and secure in life — emotionally, financially or physically.', 'Security provides the foundation for confidence and risk-taking. This theme explores how stability is built and maintained across finances, housing, health and emotional support. It recognises that perceived security is often as important as actual resources.', '#C1C8E4'),
('Lifework and resilience', 'Time management', 'I want to manage my time and energy better for balance and focus.', 'Time management reflects how energy, attention and priorities are allocated. This theme explores balance between obligation and renewal, recognising that effective use of time is closely tied to boundaries, values and wellbeing rather than productivity alone.', '#C1C8E4'),
('Lifework and resilience', 'Travel', 'I want to explore new places, cultures or perspectives.', 'Travel can broaden perspective and disrupt routine. This theme reflects exploration as a means of learning, reflection or reinvention. It recognises travel as both physical movement and internal shift — offering distance, contrast and renewed understanding of self and others.', '#C1C8E4'),
('Lifework and resilience', 'Work', 'I want to contribute through meaningful or rewarding work — paid or unpaid.', 'Work shapes identity, routine and purpose across life stages. This theme explores contribution, effort and value — paid or unpaid — recognising how work can provide meaning, structure and growth, while also requiring boundaries and alignment with personal priorities.', '#C1C8E4'),

-- Relationships and belonging (8 themes)
('Relationships and belonging', 'Advocacy', 'I want to speak up for what I believe in, or stand up for others who may not have a voice.', 'Advocacy often grows from lived experience of unfairness, silence or exclusion. It involves recognising power dynamics, navigating resistance, and choosing when and how to challenge existing systems. It can be energising and exhausting, but often brings a strong sense of alignment between personal values and collective action.', '#F6B5B5'),
('Relationships and belonging', 'Bereavement, loss', 'I''m dealing with the impact of losing someone or something important in my life.', 'Loss can fundamentally alter how someone experiences time, identity and connection. Grief may surface unexpectedly, long after the initial event. This theme reflects the ongoing work of integrating absence into everyday life, reshaping meaning, and finding ways to continue living fully alongside remembrance.', '#F6B5B5'),
('Relationships and belonging', 'Care & caring', 'I want to support and care for the people around me with love and attention.', 'Caring roles can shape identity, priorities and emotional resilience. This theme recognises the complexity of supporting others while maintaining personal boundaries, managing fatigue, and navigating responsibility. It also acknowledges the deep meaning and connection that can arise through acts of sustained care.', '#F6B5B5'),
('Relationships and belonging', 'Citizenship', 'I want to play an active role in my community, society or the world around me.', 'Citizenship reflects the relationship between the individual and the wider society. It encompasses belonging, responsibility, and participation beyond personal life. This theme invites reflection on how people contribute, influence, and find voice within shared systems, institutions and communities.', '#F6B5B5'),
('Relationships and belonging', 'Family', 'I want to feel more connected to and supported by my family relationships.', 'Family relationships can provide support, conflict, identity and obligation. This theme recognises that family structures vary widely, and that navigating expectations, boundaries and care across generations often involves reflection, renegotiation and emotional work over time.', '#F6B5B5'),
('Relationships and belonging', 'Politics', 'I want to engage with the ideas and systems shaping our society.', 'Political engagement reflects how individuals relate to power, fairness and collective decision-making. This theme explores participation through dialogue, action or advocacy, acknowledging both frustration and hope in efforts to influence societal structures and future direction.', '#F6B5B5'),
('Relationships and belonging', 'Relationships', 'I want to build or strengthen meaningful connections with others.', 'Relationships shape emotional wellbeing, identity and resilience. This theme reflects the ongoing work of connection — including communication, trust and repair. It recognises that relationships evolve over time, requiring attention, boundaries and adaptability across different life contexts.', '#F6B5B5'),
('Relationships and belonging', 'Volunteering', 'I want to give my time or skills to support others.', 'Volunteering reflects contribution beyond obligation. This theme explores generosity, reciprocity and connection through service, recognising both the social impact and personal meaning that can arise from supporting others without expectation of return.', '#F6B5B5'),

-- Self development and inner growth (10 themes)
('Self development and inner growth', 'Bravery', 'I''m ready to face fear or discomfort with courage.', 'Courage often appears in quiet, private moments rather than bold public acts. It can mean tolerating uncertainty, choosing honesty over comfort, or stepping forward without guarantees. This theme explores how growth frequently requires discomfort, and how fear can coexist with purposeful action.', '#F5DEB3'),
('Self development and inner growth', 'Confidence & grit', 'I want to believe in myself and keep going, even when things are tough.', 'Confidence and perseverance are often built through experience rather than certainty. This theme reflects how repeated effort, setbacks and persistence gradually shape self-trust. It highlights the difference between external validation and internal resilience, and how endurance supports long-term growth.', '#F5DEB3'),
('Self development and inner growth', 'Eliminating negativity', 'I want to let go of habits, thoughts or relationships that hold me back.', 'This theme reflects the process of recognising harmful cycles — internal or external — and intentionally choosing alternatives. It often involves unlearning habits, reframing self-talk, and creating distance from environments or influences that undermine wellbeing, clarity or growth.', '#F5DEB3'),
('Self development and inner growth', 'Freedom from restraints', 'I want more freedom and autonomy to live life on my own terms.', 'This theme explores breaking free from internalised rules, external pressures or inherited expectations. It often emerges during transitions, prompting reassessment of roles and assumptions. Freedom here is not escape, but conscious choice about how to live, decide and define oneself.', '#F5DEB3'),
('Self development and inner growth', 'Happiness', 'I want to feel more joy, contentment and emotional fulfilment in my life.', 'Happiness is rarely constant and often contextual. This theme invites reflection on what genuinely brings satisfaction versus what is socially prescribed. It recognises the role of mindset, circumstance and choice in cultivating moments of joy, meaning and emotional ease over time.', '#F5DEB3'),
('Self development and inner growth', 'Integrity', 'I want to stay true to my values, even when it''s not easy.', 'Integrity involves consistency between values and behaviour over time. This theme explores ethical decision-making, accountability and self-respect, particularly when choices carry consequences. It reflects how trust — in oneself and others — is built through aligned actions rather than intention alone.', '#F5DEB3'),
('Self development and inner growth', 'Letting go', 'I''m ready to let go of things that no longer serve me.', 'Letting go often follows periods of transition or tension. This theme reflects the emotional work of releasing identities, attachments or narratives that once served a purpose. It acknowledges both grief and relief, creating space for renewal, clarity and forward movement.', '#F5DEB3'),
('Self development and inner growth', 'Personal development', 'I want to grow as a person — emotionally, mentally or spiritually.', 'Personal development reflects intentional self-exploration and growth. This theme encompasses emotional intelligence, self-awareness and capability-building. It often arises from curiosity or discomfort, supporting people to evolve their thinking, behaviour and sense of agency over time.', '#F5DEB3'),
('Self development and inner growth', 'Purpose', 'I want to feel a stronger sense of meaning and motivation in my life.', 'Purpose often emerges through reflection rather than certainty. This theme explores how meaning evolves across life stages, shaped by contribution, values and connection. It acknowledges that purpose may shift, deepen or fragment, and is often discovered through action rather than planning alone.', '#F5DEB3'),
('Self development and inner growth', 'Values', 'I want to live more in line with what truly matters to me.', 'Values act as internal reference points for decision-making. This theme explores clarifying what matters most and how those principles guide choices, behaviour and relationships. It acknowledges that values may evolve with experience, challenge and changing life circumstances.', '#F5DEB3');
